### ISSUE TITLE
Enum value assignment is not working in insertDML

### ISSUE THREAD

**Issue by jobyjames1** [netspective-labs/sql-aide#10]
When we try the following scenario in test case we are getting errors 

```
 enum GraphNature {
  SERVICE = "Service",
  APP = "Application",
}

const graphNature = gm.textEnumTable(
  "graph_nature",
  GraphNature,
  { isIdempotent: true },
);

const graph = gm.autoIncPkTable("graph", {
  graph_id: autoIncPK(),
  graph_nature_code: graphNature.references.code(),
  name: text(),
  description: textNullable(),
  ...gm.housekeeping.columns,
});

//Insertion 

const graphTableInsertion = 
  graph.insertDML({
    name: "text-value",
    graph_nature_code: "SERVICE",
    description: "description",
  });
```

error output:

```

error: TypeError: this._def.values.indexOf is not a function
    if (this._def.values.indexOf(input.data) === -1) {
                         ^
    at Proxy._parse (https://deno.land/x/zod@v3.21.4/types.ts:3974:26)
    at ZodObject._parse (https://deno.land/x/zod@v3.21.4/types.ts:2275:29)
    at ZodObject._parseSync (https://deno.land/x/zod@v3.21.4/types.ts:212:25)
    at ZodObject.safeParse (https://deno.land/x/zod@v3.21.4/types.ts:246:25)
    at ZodObject.parse (https://deno.land/x/zod@v3.21.4/types.ts:225:25)
    at https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.0.14/render/ddl/table/record.ts:144:27
    at Object.insertDML (https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.0.14/render/dml/insert.ts:288:28)
    at file:///home/joby/workspaces/github.com/netspective-labs/sql-aide/pattern/typical/enum-table_test.ts:269:13
```

While we trying to generate the graph table in the existing test case working fine. For example 

```
await tc.step("insert enum values graph table", () => {
    const tcf = SQLa.tableColumnFactory<Any, Any>();
    const keys = SQLa.primaryKeyColumnFactory();

    const graph = SQLa.tableDefinition("graph", {
      graph_id: keys.primaryKey(z.string()),
      graph_nature_code: graphNature.references.code(),
      name: tcf.unique(z.string()),
      description: tcf.unique(z.string()),
    });

    ta.assertEquals(
      uws(`
      CREATE TABLE "graph" (
          "graph_id" TEXT PRIMARY KEY NOT NULL,
          "graph_nature_code" TEXT NOT NULL,
          "name" TEXT /* UNIQUE COLUMN */ NOT NULL,
          "description" TEXT /* UNIQUE COLUMN */ NOT NULL,
          FOREIGN KEY("graph_nature_code") REFERENCES "graph_nature"("code"),
          UNIQUE("name"),
          UNIQUE("description")
      )`),
      graph.SQL(ctx),
    );
  });
```

**Comment by shah** [comment]
@jobyjames1 @geovlazar please share your Typescript import line so I can see what version you're using.

**Comment by shah** [comment]
I've added a test case for this ticket and I attempted to create the same pattern as your bug but was not able to reproduce it. See 56f556d8e0b72fd42ea46714087ac27e425101f7 and adjust that test case or update it to match more closely your problem.
