### ISSUE TITLE
Enum value assignment in Insert DML throws an exception

### ISSUE THREAD

**Issue by shah** [netspective-labs/sql-aide#9]
When attempting to assign an enum value as a foreign key reference in a table row:

```typescript
console.log(syntheticRF.insertDML({  synthetic_table_id: "synthetic01", text: "text", text_enum_code: "code1" }).SQL(ctx))
```

An exception is thrown since enum values are not being copied during a clone of a Zod type:

```
error: TypeError: this._def.values.indexOf is not a function
    if (this._def.values.indexOf(input.data) === -1) {
                         ^
    at Proxy._parse (https://deno.land/x/zod@v3.21.4/types.ts:3974:26)
    at ZodObject._parse (https://deno.land/x/zod@v3.21.4/types.ts:2275:29)
    at ZodObject._parseSync (https://deno.land/x/zod@v3.21.4/types.ts:212:25)
    at ZodObject.safeParse (https://deno.land/x/zod@v3.21.4/types.ts:246:25)
    at ZodObject.parse (https://deno.land/x/zod@v3.21.4/types.ts:225:25)
    at file:///home/snshah/workspaces/github.com/netspective-labs/sql-aide/render/ddl/table/record.ts:144:27
    at Object.insertDML (file:///home/snshah/workspaces/github.com/netspective-labs/sql-aide/render/dml/insert.ts:288:28)
    at file:///home/snshah/workspaces/github.com/netspective-labs/sql-aide/pattern/typical/enum-table_test.ts:182:19
```

**Comment by jobyjames1** [comment]
We verified the updated test case, it was working fine but at the same time we tried the following table

```
CREATE TABLE IF NOT EXISTS "graph" (
    "graph_id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "graph_nature_code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT DEFAULT 'UNKNOWN',
    FOREIGN KEY("graph_nature_code") REFERENCES "graph_nature"("code")
)

 ta.assertEquals(
      `INSERT INTO "graph" ("graph_id", "graph_nature_code", "name", "description") VALUES ('graph01', 'SERVICE', 'test name', 'test desctription')`,
      graphRF.insertDML({
        graph_id: "graph01",
        graph_nature_code: "SERVICE",
        description: "test desctription",
        name: "test name",
      }).SQL(ctx),
    );


//	it shows the error 
	

error: TypeError: this._def.values.indexOf is not a function
    if (this._def.values.indexOf(input.data) === -1) {
                         ^
    at Proxy._parse (https://deno.land/x/zod@v3.21.4/types.ts:3974:26)
    at ZodObject._parse (https://deno.land/x/zod@v3.21.4/types.ts:2275:29)
    at ZodObject._parseSync (https://deno.land/x/zod@v3.21.4/types.ts:212:25)
    at ZodObject.safeParse (https://deno.land/x/zod@v3.21.4/types.ts:246:25)
    at ZodObject.parse (https://deno.land/x/zod@v3.21.4/types.ts:225:25)
    at https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.0.14/render/ddl/table/record.ts:144:27
    at Object.insertDML (https://raw.githubusercontent.com/netspective-labs/sql-aide/v0.0.14/render/dml/insert.ts:288:28)
    at file:///home/joby/workspaces/github.com/netspective-labs/sql-aide/pattern/typical/enum-table_test.ts:269:13
```
	
	
and also we tried with 

```
  const graphRF = SQLa.tableColumnsRowFactory(
      graph.tableName,
      graph.zoSchema.shape,
    );



//	it shows the error 

	error: Error: Unable to map Zod type ZodOptional to SQL domain, invalid from hook name 'created_by' ({"innerType":{"_def":{"checks":[],"typeName":"ZodString","coerce":false,"description":"{\"isSqlDomainZodDescrMeta\":true,\"zodTypeSqlDomainFrom\":\"created_by\"}","sqlDomain":{"isSqlDomain":true,"identity":"created_by","lintIssues":[],"tableName":"billing","columnName":"created_by"},"isSqlDomainProxy":true}},"typeName":"ZodOptional","description":"{\"isSqlDomainZodDescrMeta\":true,\"zodTypeSqlDomainFrom\":\"created_by\"}"} init: {"identity":"created_by"})
      throw new Error(
            ^
    at from (file:///home/joby/workspaces/github.com/netspective-labs/sql-aide/render/domain/domain.ts:729:13)
    at Object.cacheableFrom (file:///home/joby/workspaces/github.com/netspective-labs/sql-aide/render/domain/domain.ts:872:12)
    at Module.foreignKeysFactory (file:///home/joby/workspaces/github.com/netspective-labs/sql-aide/render/ddl/table/foreign-key.ts:135:15)
    at Module.tableDefinition (file:///home/joby/workspaces/github.com/netspective-labs/sql-aide/render/ddl/table/table.ts:66:18)
    at Module.tableColumnsRowFactory (file:///home/joby/workspaces/github.com/netspective-labs/sql-aide/render/ddl/table/record.ts:30:16)
    at file:///home/joby/workspaces/github.com/netspective-labs/sql-aide/pattern/typical/enum-table_test.ts:254:26
	
```	
The difference between the test table and the actual table is as follows` INTEGER PRIMARY KEY AUTOINCREMENT` vs `TEXT PRIMARY KEY`. This works with `TEXT PRIMARY KEY` only as per our evaluation

```
//Actual Table
CREATE TABLE IF NOT EXISTS "graph" (
    "graph_id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "graph_nature_code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT DEFAULT 'UNKNOWN',
    FOREIGN KEY("graph_nature_code") REFERENCES "graph_nature"("code")
)

//Generated table which works test cases
 CREATE TABLE "graph" (
          "graph_id" TEXT PRIMARY KEY NOT NULL,
          "graph_nature_code" TEXT NOT NULL,
          "name" TEXT /* UNIQUE COLUMN */ NOT NULL,
          "description" TEXT /* UNIQUE COLUMN */ NOT NULL,
          FOREIGN KEY("graph_nature_code") REFERENCES "graph_nature"("code"),
          UNIQUE("name"),
          UNIQUE("description")
      )
	  
```	  
Can you please suggest any solution for this?
